flags: {}
packages:
- '.'
- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 4a05941738bf908eecc5c2ac336c884ef325d0fa
  extra-dep: true
- location:
    git: https://github.com/alanz/ghc-exactprint.git
    commit: 4b8c3aa4e4e5ccfa5d171dd7285f1c33abe69567
  extra-dep: true
extra-deps:
- Strafunski-StrategyLib-5.0.0.8
- cabal-helper-0.4.0.0
- rosezipper-0.2
- syz-0.2.0.0
# resolver: nightly-2015-07-30
resolver: nightly-2015-08-06
# Use system GHC, must be a 7.10.2 rc or later.
# system-ghc: true
